version: '2'
services:
  cuptodate:
    build: .
    container_name: "cuptodate"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8001:80'
    environment:
      DATABASE_HOST: "database"
      DATABASE_NAME: "cuptodate"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "secretpassword"
      DOCKER_API_VERSION: "v1.41"
      INTERNAL_UPDATE_INTERVAL: 1
      DO_NOT_LOOK_FOR_UPDATE_BEFORE: 30
  #********************************************
  # DATABASE
  #********************************************
  database:
    image: mysql:8.0
    container_name: "database"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: cuptodate
      MYSQL_ROOT_PASSWORD: secretpassword
